version: '3'

services:
  web:
    build: .
    command: gunicorn kaizen.wsgi --bind 0.0.0.0:8001
    ports:
      - "8001:8001"
    networks:
      - backend
    volumes:
      - .:/code

  nginx:
    image: nginx:latest
    ports:
      - 8088:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./mysite/static:/code/static
    environment:
      DJANGO_WEB_HOST: "web"

networks:
  backend:
    driver: bridge
