version: '3'

services:
  web:
    build: .
    ports:
      - "8001:8001"
    networks:
      - backend
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      DJANGO_WEB_HOST: "web"
    # command: gunicorn kaizen.wsgi --bind 0.0.0.0:8001

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./kaizen/static:/code/static
    depends_on:
      - web
    environment:
      DJANGO_WEB_HOST: "web"
    networks:
      - backend

  redis:
    image: redislabs/redismod
    ports:
      - 6379:6379
    volumes:
      - ./data:/code/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      DJANGO_REDIS_HOST: "redis"
    networks:
      - backend

networks:
  backend:
    driver: bridge
