version: '3'

services:
  web:
    build: .
    command: gunicorn kaizen.wsgi --bind 0.0.0.0:8001
    ports:
      - "8001:8001"
    networks:
      - backend
    volumes:
      - .:/code
    environment:
      DJANGO_WEB_HOST: "web"

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./kaizen/static:/code/static
    depends_on:
      - web
    environment:
      DJANGO_WEB_HOST: "web"
    networks:
      - backend

networks:
  backend:
    driver: bridge
